/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedBackground: typeof import('./components/AnimatedBackground.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    DynamicTopology: typeof import('./components/DynamicTopology.vue')['default']
    FeatureCard: typeof import('./components/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./components/FeaturesSection.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GitHubStarButton: typeof import('./components/GitHubStarButton.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    ParticleBackground: typeof import('./components/ParticleBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TranslateIcon: typeof import('./components/icons/TranslateIcon.vue')['default']
  }
}
