/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    DynamicTopology: typeof import('./components/DynamicTopology.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FeatureCard: typeof import('./components/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./components/FeaturesSection.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GitHubStarButton: typeof import('./components/GitHubStarButton.vue')['default']
    ParticleBackground: typeof import('./components/ParticleBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TranslateIcon: typeof import('./components/icons/TranslateIcon.vue')['default']
  }
}
